Repository googlemaps/google-maps-services-java, pull requests merged in 2019-09, with the labels that each got.

#597 add subfields to mask values for place details request
  src/main/java/com/google/maps/PlaceDetailsRequest.java
Labels: cla: yes, triage me

#598 add changelog
  CHANGELOG.md
Labels: cla: yes

#601 Add tourist_attraction address type
  src/main/java/com/google/maps/model/AddressType.java
  src/test/java/com/google/maps/model/EnumsTest.java
Labels: cla: yes

#606 Fixes bug where deps were not in pom.xml and bumps to 0.10.1
  build.gradle
  gradle.properties
Labels: cla: yes

#605 deprecation warning for place fields: `alt_id`, `id`, `reference`, and `scope`
  CHANGELOG.md
  src/main/java/com/google/maps/PlaceDetailsRequest.java
  src/main/java/com/google/maps/model/PlaceIdScope.java
  src/main/java/com/google/maps/model/PlacesSearchResult.java
  src/test/java/com/google/maps/PlacesApiTest.java
Labels: cla: yes, semver: patch

#608 add additional place types and deprecate others
  CHANGELOG.md
  src/main/java/com/google/maps/model/PlaceType.java
  src/test/java/com/google/maps/PlacesApiTest.java
Labels: cla: yes, semver: patch

#612 direct users to javadoc.io instead of github pages
  README.md
Labels: cla: yes, semver: patch
